version: '3.3'

services:
  mqtt-app:
    container_name: mqtt-dev
    build:
      context: .
      dockerfile: Dockerfile   
    env_file:
      - .env
    volumes:
      - /home/hustller/go/src/github.com/mzfarshad/Mqtt-test/.env:/mqtt-app/.env
      - .:/app
    depends_on:
      - db
    networks:
      - mqtt-dev-connection

  # db:
  #   container_name: mqtt-db
  #   image: postgres:14
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASS} 
  #     - POSTGRES_DB=${DB_NAME}
  #     - TZ=${DB_TIMEZONE}   
  #   ports:
  #     - "${DB_PORT}:5432"
  #   expose:
  #     - 5432
  #   restart: unless-stopped
  #   volumes:
  #     - data:/data/postgres
  #   networks:
  #     - mqtt-dev-connection

volumes:
  data:
    driver: local

networks:
  mqtt-dev-connection:
    driver: bridge
